export default {
  test: '/',
  getIndexMenus: '/controller/appMenu/list',
  phonePwdLogin: '/api/pwd/login',
  uploadUrl: '/common/upload',
  getSortList: '/goods/goodsCategory/list',
  addSecondhandGoods: '/goods/secondhandGoods',
  loginOut: '/logout',
  getUserInfo: '/api/getInfo',
  updateMember: '/info/member',
  listShopGoods: '/goods/shopGoods/list',
  addAddress: '/order/address',
  listAddress: '/order/address/list',
  delAddress: '/order/address/',
  getAddress: '/order/address/',
  addShopOrder: '/order/shopOrder',
  listShopOrder: '/order/shopOrder/list',
  updateShopOrder: '/order/shopOrder',
  getSecondhandGoodsList: '/goods/secondhandGoods/list',
  getSecondhandGoodsListSelf: '/goods/secondhandGoods/publishList',
  listInfo:'/activity/info/list',
  getListInfo:'/activity/info/'
}
